=== mbarlow12/OPGEEv4/opgee/etc/opgee.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>

  <!-- 1. Attribute Definitions -->

  <xs:element name='AttrDefs'>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref='ClassAttrs' maxOccurs='unbounded'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name='ClassAttrs'>
    <xs:complexType>
      <xs:choice maxOccurs='unbounded'>
        <xs:element minOccurs='0' ref='Options'/>
        <xs:element minOccurs='0' ref='AttrDef'/>
    </xs:choice>
      <xs:attribute name='name' use='required' type='xs:NCName'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='Options'>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs='unbounded' ref='Option'/>
      </xs:sequence>
      <xs:attribute name='name' use='required' type='xs:string'/>
      <xs:attribute name='default' use='required' type='xs:string'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='Option'>
    <xs:complexType mixed='true'>
      <xs:attribute name='desc' type='xs:string'/>
      <xs:attribute name='label' type='xs:string'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='AttrDef'>
    <xs:complexType mixed='true'>
      <xs:attribute name='desc'/>
      <xs:attribute name='name' use='required' type='xs:string'/>
      <xs:attribute name='options' type='xs:string'/>
      <xs:attribute name='type' type='xs:NCName'/>
      <xs:attribute name='unit'/>
            <xs:attribute name='exclusive'/>      <!-- exclusive binary attributes; only one can be 1 -->
            <xs:attribute name='synchronized'/>   <!-- synchronized attributes; must have the same value -->

      <!-- Numeric constraints -->
      <xs:attribute name="GT" type="xs:decimal"/>
      <xs:attribute name="GE" type="xs:decimal"/>
      <xs:attribute name="LT" type="xs:decimal"/>
      <xs:attribute name="LE" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>

  <!-- end of Attribute Definitions -->

  <!-- 2. Analysis and Field Definitions -->

	<!-- Attribute types -->
	<xs:simpleType name="PhaseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="gas"/>
			<xs:enumeration value="liquid"/>
			<xs:enumeration value="solid"/>
    </xs:restriction>
	</xs:simpleType>

	<xs:element name='Model'>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element minOccurs='0' ref="AttrDefs"/>
				<xs:element minOccurs='0' ref="A"/>
				<xs:element minOccurs='0' ref="Analysis"/>
        <xs:element minOccurs='0' ref='Field'/>
        <xs:element minOccurs="0" ref='TableUpdate'/>
			</xs:choice>
      <xs:attribute name='schema_version' use='optional' type='xs:string'/> <!-- default is "4.0.0.a" -->
		</xs:complexType>
    </xs:element>

	<xs:element name='Analysis'>
    <xs:complexType>
			<xs:choice maxOccurs='unbounded'>
        <xs:element ref='A'/>
        <xs:element minOccurs='0' ref='FieldRef'/>
        <xs:element minOccurs='0' ref='Group'/>   <!-- field groups to include in this analysis -->
      </xs:choice>
      <xs:attribute name='name' use='required' type='xs:NCName'/>
      <xs:attribute name='delete' type='xs:boolean'/>
    </xs:complexType>
	</xs:element>

	<xs:element name='Group'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
			    <xs:attribute name='regex' default='0' type='xs:boolean'/>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

	<xs:element name='Field'>
    <xs:complexType>
      <xs:choice maxOccurs='unbounded'>
        <xs:element minOccurs='0' ref='A'/>
        <xs:element minOccurs='0' ref='Group'/>       <!-- groups this field belongs to -->
        <xs:element minOccurs='0' ref='Aggregator'/>
				<xs:element minOccurs='0' ref='Process'/>
  			<xs:element minOccurs='0' ref='ProcessChoice'/>
				<xs:element ref='Stream'/>
      </xs:choice>
			<xs:attribute name='name' use='required' type='xs:string'/>
			<xs:attribute name='enabled' default='1' type='xs:boolean'/>
			<xs:attribute name='extend' default='0' type='xs:boolean'/>
      <xs:attribute name='delete' type='xs:boolean'/>
      <xs:attribute name="modifies" type="xs:string"/>
      <xs:attribute name="modified" type="xs:string"/>    <!-- set after a modified field has been copied to avoid doing so again -->
    </xs:complexType>
  </xs:element>

  <xs:element name="Cell">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='row' use='required' type='xs:string'/>
          <xs:attribute name='col' use='required' type='xs:string'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="TableUpdate">
    <xs:complexType>
      <xs:choice maxOccurs='unbounded'>
        <xs:element minOccurs='1' ref='Cell'/>
      </xs:choice>
      <xs:attribute name='name' use='required' type='xs:string'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='A'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='name' use='required' type='xs:NCName'/>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
	</xs:element>

	<!-- use type forward reference to define recursive structure -->
	<xs:element name="Aggregator" type="AggregatorType"/>

	<xs:complexType name="AggregatorType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Aggregator" type="AggregatorType"/>
			<xs:element minOccurs='0' ref='A'/>
			<xs:element minOccurs='0' ref='Process'/>
			<xs:element minOccurs='0' ref='ProcessRef'/>
			<xs:element minOccurs='0' ref='ProcessChoice'/>
		</xs:choice>
		<xs:attribute name='name' type='xs:string'/>
		<xs:attribute name='enabled' default='1' type='xs:boolean'/>
    <xs:attribute name='delete' type='xs:boolean'/>
	</xs:complexType>

  <!-- identifier for stream contents -->
  <xs:element name='Contains'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name='Stream'>
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="3" ref='A'/>
        <xs:element ref='Component'/>
        <xs:element ref="Contains"/>
      </xs:choice>
      <xs:attribute name='name'/>                      <!-- computed if not provided -->
      <xs:attribute name='src' use='required'/>
      <xs:attribute name='dst' use='required'/>
      <xs:attribute name="impute" default="1"/>        <!-- if false, don't traverse during impute() processing -->
      <xs:attribute name="boundary" type='xs:string'/>
      <xs:attribute name='delete' type='xs:boolean'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='Component'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:decimal'>
          <xs:attribute name='name' use='required'/>
          <xs:attribute name='phase' use='required' type="PhaseType"/>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

	<xs:element name='Process'>
    <xs:complexType>
			<xs:choice maxOccurs="unbounded">
        <xs:element minOccurs='0' ref='A'/>
      </xs:choice>
      <xs:attribute name='class' use='required'/>
      <xs:attribute name='name' type='xs:NCName'/>
      <xs:attribute name='desc' type='xs:string'/>
      <xs:attribute name='enabled' default='1' type='xs:boolean'/>
      <xs:attribute name='extend' default='0' type='xs:boolean'/>
      <xs:attribute name='impute-start' default='0' type='xs:boolean'/>
      <xs:attribute name='cycle-start' default='0' type='xs:boolean'/>
      <xs:attribute name="boundary" type='xs:string'/>
      <xs:attribute name='delete' type='xs:boolean'/>
      <xs:attribute name='after' type='xs:boolean'/>  <!-- run this process after "normal" processing completes -->
    </xs:complexType>
	</xs:element>

	<!-- use type forward reference to define recursive structure -->
	<xs:element name="ProcessChoice" type="ProcessChoiceType"/>

	<xs:complexType name="ProcessChoiceType">
		<xs:choice maxOccurs="unbounded">
 				<xs:element minOccurs='1' ref='ProcessGroup'/>
		</xs:choice>
    <xs:attribute name='name' use='required' type='xs:string'/>
    <xs:attribute name='extend' default='0' type='xs:boolean'/>
    <xs:attribute name='default' type='xs:string'/>
    <xs:attribute name='delete' type='xs:boolean'/>
	</xs:complexType>

	<xs:element name='ProcessGroup'>
    <xs:complexType>
      <xs:choice maxOccurs='unbounded'>
 				<xs:element minOccurs='0' ref='ProcessRef'/>
				<xs:element minOccurs='0' ref='StreamRef'/>
 				<xs:element minOccurs='1' ref='ProcessChoice'/>
      </xs:choice>
			<xs:attribute name='name' use='required' type='xs:string'/>
      <xs:attribute name='delete' type='xs:boolean'/>
    </xs:complexType>
  </xs:element>

	<xs:element name='FieldRef'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='name' use='required' type='xs:string'/>
          <!-- Allow 'regex' attribute here? -->
			    <!-- xs:attribute name='regex' default='0' type='xs:boolean' -->
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

	<xs:element name='ProcessRef'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='name' type='xs:string'/>
          <xs:attribute name='class' type='xs:string'/>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name='StreamRef'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='name' use='required' type='xs:string'/>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== mbarlow12/OPGEEv4/tests/files/gas_lifting_field.xml
<?xml version='1.0' encoding='UTF-8'?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schema_version="4.0.0.a" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">
  <Analysis name="example">
    <A name="functional_unit">oil</A>
    <A name="GWP_horizon">100</A>
    <A name="GWP_version">AR5</A>
    <FieldRef name="gas_lifting_field"/>
  </Analysis>
  <Field name="gas_lifting_field" modifies="template">
    <A name="API">8.6</A>
    <A name="FOR">99.9</A>
    <A name="GFIR">166.5</A>
    <A name="GLIR">363.8</A>
    <A name="GOR">111.0</A>
    <A name="SOR">0.0</A>
    <A name="WIR">1.1</A>
    <A name="WOR">0.1</A>
    <A name="age">13.0</A>
    <A name="country">Venezuela</A>
    <A name="depth">2200.0</A>
    <A name="downhole_pump">1</A>
    <A name="ecosystem_richness">High carbon</A>
    <A name="field_development_intensity">High</A>
    <A name="flood_gas_type">NG</A>
    <A name="frac_CO2_breakthrough">59</A>
    <A name="frac_transport_barge">0.0</A>
    <A name="frac_transport_pipeline">1.0</A>
    <A name="frac_transport_rail">0.0</A>
    <A name="frac_transport_tanker">1.0</A>
    <A name="frac_transport_truck">0.0</A>
    <A name="frac_venting">0.002</A>
    <A name="fraction_elec_onsite">1.0</A>
    <A name="fraction_remaining_gas_inj">0.0</A>
    <A name="fraction_steam_cogen">0.0</A>
    <A name="fraction_steam_solar">0.0</A>
    <A name="fraction_water_reinjected">0.0</A>
    <A name="gas_comp_C1">91.9</A>
    <A name="gas_comp_C2">0.86</A>
    <A name="gas_comp_C3">0.39</A>
    <A name="gas_comp_C4">0.85</A>
    <A name="gas_comp_CO2">5.9</A>
    <A name="gas_comp_H2S">0.0</A>
    <A name="gas_comp_N2">0.1</A>
    <A name="gas_flooding">0</A>
    <A name="gas_lifting">0</A>
    <A name="gas_processing_path">Acid Wet Gas</A>
    <A name="name">Hamaca</A>
    <A name="natural_gas_reinjection">0</A>
    <A name="num_prod_wells">190</A>
    <A name="num_water_inj_wells">0</A>
    <A name="offshore">0.0</A>
    <A name="oil_processing_path">Upgrading</A>
    <A name="oil_prod">158441.0</A>
    <A name="oil_sands_mine">None</A>
    <A name="prod_index">10.0</A>
    <A name="prod_water_inlet_temp">140.0</A>
    <A name="res_press">950.0</A>
    <A name="res_temp">109.6</A>
    <A name="stabilizer_column">0</A>
    <A name="steam_flooding">0</A>
    <A name="transport_dist_barge">500.0</A>
    <A name="transport_dist_pipeline">140.0</A>
    <A name="transport_dist_rail">800.0</A>
    <A name="transport_dist_tanker">2443.0</A>
    <A name="transport_dist_truck">100.0</A>
    <A name="upgrader_type">Delayed coking</A>
    <A name="water_flooding">0</A>
    <A name="water_reinjection">0</A>
    <A name="well_diam">5.5</A>
    <Process class="CrudeOilDewatering">
      <A name="heater_treater">1</A>
    </Process>
    <Process class="HeavyOilDilution">
      <A name="fraction_diluent">0.0</A>
    </Process>
    <Aggregator name="ProductionExtraction">
      <ProcessRef class="CrudeOilDewatering"/>
    </Aggregator>
    <Aggregator name="SurfaceProcessing">
      <ProcessRef class="HeavyOilDilution"/>
    </Aggregator>
  </Field>
</Model>
